feat(terraform): skip Apply if no changes present

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -124,7 +124,17 @@ jobs:
       # Ref: https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#plan-and-apply-on-different-machines
       - name: Terraform Plan
         id: plan
-        run: terraform plan -input=false -out=tfplan
+        # Start Bash without fail-fast behavior.
+        # Required in order to explicitly check exitcode.
+        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
+        shell: bash {0}
+        run: |
+          terraform plan -input=false -out=tfplan -detailed-exitcode
+          exitcode=$?
+          if [[ "$exitcode" == 1 ]]; then
+            exit "$exitcode"
+          fi
+          echo "exitcode=$exitcode" >> "$GITHUB_OUTPUT"
 
       # Some plans are too large to be stored in environment variables or step outputs, resulting in an error.
       # To bypass this, the plan must be explicitly read during this step using the "terraform show" command.
@@ -156,12 +166,16 @@ jobs:
 
       - name: Archive Terraform config
         id: archive
+        # Only run if Terraform Plan succeeded with non-empty diff (changes present).
+        # Ref: https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode
+        if: steps.plan.outputs.exitcode == 2
         run: |
           tar -cf terraform.tar .
           7z a -p"$ENCRYPTION_PASSWORD" terraform.tar.7z terraform.tar
 
       - name: Upload artifact
         id: upload
+        if: steps.archive.outcome == 'success'
         uses: actions/upload-artifact@v3
         with:
           name: ${{ inputs.artifact_name }}
@@ -175,6 +189,7 @@ jobs:
   terraform-apply:
     name: Terraform Apply
     needs: terraform-plan
+    if: needs.terraform-plan.outputs.upload-outcome == 'success'
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
     defaults:
